/* Copyright (C) 2023 Harry Clark */

/* SEGA Dreamcast Raspberry Pi Pico Interface */

/* THIS FILE PERTAINS TO THE FUNCTIONALTIY AND METHODS OF THE CONTROLLER */
/* BUS RELATIVE TO THE SEGA DREAMCAST'S HARDWARE */

/* THE MAPLE BUS IS AN ARCHITECTURE EXCLUSIVE TO THE SEGA DREAMCAST */
/* THAT SUPPORTS THE COMMUNICATIONS BETWEEN PERIPHERALS */

#ifndef MAPLE_MAIN
#define MAPLE_MAIN

#include "common.h"

#define MAPLE_BUS_ID U32
#define MAPLE_PORT U32
#define MAPLE_ADDRESS U32

VOID_FUNCTION(MAPLE_INIT);
VOID_FUNCTION(MAPLE_SET_VIBRATION);
VOID_FUNCTION(MAPLE_GET_INPUT);
VOID_FUNCTION(MAPLE_GET_ABSOLUTE_COORD);
VOID_FUNCTION(MAPLE_GET_KEYBOARD);
VOID_FUNCTION(MAPLE_GET_MOUSE);
VOID_FUNCTION(MAPLE_SET_VMU);

#endif
