/* Copyright (C) 2023 Harry Clark */

/* SEGA Dreamcast Raspberry Pi Pico Interface */

/* THIS FILE PERTAINS TO THE FUNCTIONALITY OF THE MAPLE BUS' */
/* FUNCTIONS CODES AS ESTABLISHED BY IT'S OWN PREPRIATORY DOCUMENTATION */

/* THE IDEA BEHIND THIS FILE IS TO PROVIDE THE HEX VALUES PROVIDED BY */
/* THE DOCUMENTATION THAT PERTAIN TO THE DREAMCAST'S PERIPHERALS AND FEATURES */

/* DOCUMENTATION INCLUDED: https://dreamcast.wiki/Maple_bus */
/* SEE: PAYLOAD TYPES - FUNCTION CODES */

#ifndef MAPLE_FUNCTION
#define MAPLE_FUNCION

/* NESTED INCLUDES */

#include "maple.h"

#define CONTROLLER 0x0100000
#define STORAGE 0x0200000
#define VMU 0x0400000

#endif