/* Copyright (C) 2023 Harry Clark */

/* SEGA Dreamcast Raspberry Pi Pico Interface */

/* THIS FILE PERTAINS TO THE FUNCTIONALITY OF THE MAPLE BUS' */
/* FUNCTIONS CODES AS ESTABLISHED BY IT'S OWN PREPRIATORY DOCUMENTATION */

/* THE IDEA BEHIND THIS FILE IS TO PROVIDE THE HEX VALUES PROVIDED BY */
/* THE DOCUMENTATION THAT PERTAIN TO THE DREAMCAST'S PERIPHERALS AND FEATURES */

/* DOCUMENTATION INCLUDED: https://dreamcast.wiki/Maple_bus */
/* SEE: PAYLOAD TYPES - FUNCTION CODES */

#ifndef MAPLE_FUNCTION
#define MAPLE_FUNCION

/* NESTED INCLUDES */

#include "maple.h"

#ifndef PAYLOAD_FUNCTION_CODES
#define PAYLOAD_FUNCTION_CODES

#define CONTROLLER 0x0100000
#define STORAGE 0x0200000
#define VMU 0x0400000
#define TIMER 0x0800000
#define AUDIO 0x10000000
#define AR_GUN 0x20000000
#define KEYBOARD 0x40000000
#define GUN 0x80000000
#define VIBRATION 0x100000000
#define MOUSE 0x200000000

#endif

#endif
